baseURL = 'https://ramzanbhutto.github.io/'
languageCode = 'en-us'
title = 'Muhammad Ramzan'
theme = 'hugo-PaperMod'


[params.homeInfoParams]
Title = "Hi, It's Ramzan"
Content = "Aspiring System Architect"

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/muhammad-ramzan-555230332/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/ramzanbhutto"

[[params.socialIcons]]
name = "Discord"
url = "https://discord.com/users/1283507507859292210"

[[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 300
    url = "/tags/"

[[menu.main]]
  name = "Search"
  url = "/search"

[[menu.main]]
  name = "Archives"
  url = "/archives"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowToc = true
ShowReadingTime = true
tags = true
ShowPostNavLinks = true
ShowShareButtons = true


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]
